version: '3'

services:
  temporal:
    image: temporalio/auto-setup:1.22.3
    ports:
      - "7233:7233"
    environment:
      - CASSANDRA_SEEDS=cassandra
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    depends_on:
      - cassandra
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

  temporal-admin-tools:
    image: temporalio/admin-tools:1.22.3
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233

  temporal-web:
    image: temporalio/web:1.15.0
    ports:
      - "8088:8088"
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    depends_on:
      - temporal

  cassandra:
    image: cassandra:3.11.9
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=temporal
    volumes:
      - cassandra-data:/var/lib/cassandra

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - temporal
    environment:
      - TEMPORAL_HOST=temporal
      - TEMPORAL_PORT=7233
    volumes:
      - .:/app

volumes:
  cassandra-data: